// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVS2LK0CsSElNUbzrfJWdnntnbeMjF45k',
    appId: '1:603658562096:web:e66c55bc7c5ad571789bf5',
    messagingSenderId: '603658562096',
    projectId: 'hypermart-a4117',
    authDomain: 'hypermart-a4117.firebaseapp.com',
    storageBucket: 'hypermart-a4117.firebasestorage.app',
    measurementId: 'G-D17T13PFRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5X0PbvmHnlDMHzS4uBTDJjVO2gtKLZ2g',
    appId: '1:603658562096:android:399f9b0c4c6249e5789bf5',
    messagingSenderId: '603658562096',
    projectId: 'hypermart-a4117',
    storageBucket: 'hypermart-a4117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ-Blo_usdaADMXnTU6vphG37692lCPwA',
    appId: '1:603658562096:ios:184e916b124e3544789bf5',
    messagingSenderId: '603658562096',
    projectId: 'hypermart-a4117',
    storageBucket: 'hypermart-a4117.firebasestorage.app',
    iosBundleId: 'com.example.hypermart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ-Blo_usdaADMXnTU6vphG37692lCPwA',
    appId: '1:603658562096:ios:184e916b124e3544789bf5',
    messagingSenderId: '603658562096',
    projectId: 'hypermart-a4117',
    storageBucket: 'hypermart-a4117.firebasestorage.app',
    iosBundleId: 'com.example.hypermart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVS2LK0CsSElNUbzrfJWdnntnbeMjF45k',
    appId: '1:603658562096:web:b3459ad1993e4dab789bf5',
    messagingSenderId: '603658562096',
    projectId: 'hypermart-a4117',
    authDomain: 'hypermart-a4117.firebaseapp.com',
    storageBucket: 'hypermart-a4117.firebasestorage.app',
    measurementId: 'G-R6YGMJPLKH',
  );
}
